name: Unit Tests

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

    workflow_dispatch:

jobs:
    lint:
        name: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Run lint
              run: |
                  npm install
                  npm run lint
                  npm run format

    test:
        name: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Run tests
              run: |
                  npm install
                  npm run test
